# Generated by Django 5.0.6 on 2024-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rename_ksiazka_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
