# Generated by Django 5.0.6 on 2024-06-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_cover_image_alter_book_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
