# Generated by Django 5.0.6 on 2024-06-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_alter_book_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[
                    ("Polish", "Polski"),
                    ("Ukrainian", "Ukraiński"),
                    ("English", "Angielski"),
                ],
                default="Polish",
                max_length=50,
            ),
        ),
    ]
