# Generated by Django 5.0.6 on 2024-06-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_book_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="modified_ebook",
            field=models.BooleanField(default=False),
        ),
    ]
